In [70]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model
from sklearn.metrics import mean_squared_error
from IPython.core.interactiveshell import InteractiveShell

df_survey_schema = pd.read_csv('survey_results_schema.csv')

df_answers = pd.read_csv('survey_results_public.csv',
                         usecols = ['Respondent', 'Hobbyist', 'Age1stCode', 'YearsCode', 'YearsCodePro', 'CompFreq', 'ConvertedComp', 'WorkWeekHrs', 'Age', 'Student', 'BetterLife'],
                        index_col = ['Respondent'])
pd.options.display.max_columns = None
df_answers.head()

Hobbyist         Student YearsCode Age1stCode      YearsCodePro  \
Respondent                                                                   
1               Yes              No         4         10               NaN   
2                No  Yes, full-time       NaN         17               NaN   
3               Yes              No         3         22                 1   
4                No              No         3         16  Less than 1 year   
5               Yes              No        16         14                 9   

           CompFreq  ConvertedComp  WorkWeekHrs BetterLife   Age  
Respondent                                                        
1               NaN            NaN          NaN        Yes  14.0  
2               NaN            NaN          NaN        Yes  19.0  
3           Monthly         8820.0         40.0        Yes  28.0  
4            Yearly        61000.0         80.0        Yes  22.0  
5               NaN            NaN         55.0        Yes  30.0

In [71]:
df_answers.shape

(88883, 10)

In [72]:
pd.unique(df_answers.Age1stCode)

array(['10', '17', '22', '16', '14', '15', '11', '20', '13', '18', '12',
       '19', '21', '8', '35', '6', '9', '29', '7', '5', '23', '30', nan,
       '27', '24', 'Younger than 5 years', '33', '25', '26', '39', '36',
       '38', '28', '31', 'Older than 85', '32', '37', '50', '65', '42',
       '34', '40', '67', '43', '44', '60', '46', '45', '49', '51', '41',
       '55', '83', '48', '53', '54', '47', '56', '79', '61', '68', '77',
       '66', '52', '80', '62', '84', '57', '58', '63'], dtype=object)

In [73]:
df_answers.Age1stCode.replace(to_replace = {'Younger than 5 years': '4',
                                            'Older than 85': '85'}, inplace=True)

In [74]:
pd.unique(df_answers.Age1stCode)

array(['10', '17', '22', '16', '14', '15', '11', '20', '13', '18', '12',
       '19', '21', '8', '35', '6', '9', '29', '7', '5', '23', '30', nan,
       '27', '24', '4', '33', '25', '26', '39', '36', '38', '28', '31',
       '85', '32', '37', '50', '65', '42', '34', '40', '67', '43', '44',
       '60', '46', '45', '49', '51', '41', '55', '83', '48', '53', '54',
       '47', '56', '79', '61', '68', '77', '66', '52', '80', '62', '84',
       '57', '58', '63'], dtype=object)

In [75]:

df_answers.YearsCode.replace(to_replace = {'Less than 1 year': '1',
                                            'More than 50 years': '50'}, inplace=True)
pd.unique(df_answers.YearsCode)

array(['4', nan, '3', '16', '13', '6', '8', '12', '2', '5', '17', '10',
       '14', '35', '7', '1', '30', '9', '26', '40', '19', '15', '20',
       '28', '25', '22', '11', '33', '50', '41', '18', '34', '24', '23',
       '42', '27', '21', '36', '32', '39', '38', '31', '37', '29', '44',
       '45', '48', '46', '43', '47', '49'], dtype=object)

In [76]:
pd.unique(df_answers.YearsCodePro)

array([nan, '1', 'Less than 1 year', '9', '3', '4', '10', '8', '2', '13',
       '18', '5', '14', '22', '23', '19', '35', '20', '25', '7', '15',
       '27', '6', '48', '12', '31', '11', '17', '16', '21', '29', '30',
       '26', '33', '28', '37', '40', '34', '24', '39', '38', '36', '32',
       '41', '45', '43', 'More than 50 years', '44', '42', '46', '49',
       '50', '47'], dtype=object)

In [77]:
df_answers.YearsCodePro.replace(to_replace = {'Less than 1 year': '1',
                                            'More than 50 years': '50'}, inplace=True)

In [78]:
pd.unique(df_answers.YearsCodePro)

array([nan, '1', '9', '3', '4', '10', '8', '2', '13', '18', '5', '14',
       '22', '23', '19', '35', '20', '25', '7', '15', '27', '6', '48',
       '12', '31', '11', '17', '16', '21', '29', '30', '26', '33', '28',
       '37', '40', '34', '24', '39', '38', '36', '32', '41', '45', '43',
       '50', '44', '42', '46', '49', '47'], dtype=object)

In [79]:
pd.unique(df_answers.Age)

array([14. , 19. , 28. , 22. , 30. , 42. , 24. , 23. ,  nan, 21. , 31. ,
       20. , 26. , 29. , 38. , 47. , 34. , 32. , 25. , 17. , 35. , 27. ,
       44. , 43. , 62. , 37. , 45. , 18. , 33. , 36. , 16. , 39. , 64. ,
       41. , 54. , 49. , 40. , 56. , 12. , 58. , 46. , 59. , 51. , 48. ,
       57. , 52. , 50. , 23.9, 55. , 15. , 67. , 13. ,  1. , 53. , 69. ,
       65. , 17.5, 63. , 61. , 68. , 73. , 70. , 60. , 16.5, 46.5, 11. ,
       71. ,  3. , 97. , 29.5, 77. , 74. , 26.5, 26.3, 24.5, 78. , 72. ,
       66. , 76. , 10. , 75. , 99. , 83. , 79. , 36.8, 14.1, 13.5, 19.5,
       98. , 43.5, 22.5, 31.5, 21.5, 28.5, 33.6,  2. , 38.5, 30.8, 24.8,
       90. , 61.3, 81. ,  4. , 17.3, 19.9, 80. , 85. , 88. , 23.5, 16.9,
       20.9, 91. , 98.9, 57.9,  9. , 94. , 95. , 37.5, 14.5,  5. , 82. ,
       84. , 37.3, 33.5, 53.8, 31.4, 87. ])

In [80]:
df_answers.loc[df_answers['CompFreq']=='Monthly', 'ConvertedComp'] = df_answers['ConvertedComp']*12

In [81]:
df_answers.loc[df_answers['CompFreq']=='Weekly', 'ConvertedComp'] = df_answers['ConvertedComp']*52

In [82]:
df_answers.drop('CompFreq', axis=1, inplace=True)

In [83]:
df_answers.head()

Hobbyist         Student YearsCode Age1stCode YearsCodePro  \
Respondent                                                              
1               Yes              No         4         10          NaN   
2                No  Yes, full-time       NaN         17          NaN   
3               Yes              No         3         22            1   
4                No              No         3         16            1   
5               Yes              No        16         14            9   

            ConvertedComp  WorkWeekHrs BetterLife   Age  
Respondent                                               
1                     NaN          NaN        Yes  14.0  
2                     NaN          NaN        Yes  19.0  
3                105840.0         40.0        Yes  28.0  
4                 61000.0         80.0        Yes  22.0  
5                     NaN         55.0        Yes  30.0

In [84]:
df_answers.dtypes

Hobbyist          object
Student           object
YearsCode         object
Age1stCode        object
YearsCodePro      object
ConvertedComp    float64
WorkWeekHrs      float64
BetterLife        object
Age              float64
dtype: object

In [85]:
df_answers[['YearsCode','Age1stCode','YearsCodePro']] = df_answers[['YearsCode','Age1stCode','YearsCodePro']].astype('float64', copy=False)

In [86]:
df_answers.dtypes

Hobbyist          object
Student           object
YearsCode        float64
Age1stCode       float64
YearsCodePro     float64
ConvertedComp    float64
WorkWeekHrs      float64
BetterLife        object
Age              float64
dtype: object

In [87]:
df_answers.corr()

YearsCode  Age1stCode  YearsCodePro  ConvertedComp  \
YearsCode       1.000000   -0.246663      0.872745       0.010646   
Age1stCode     -0.246663    1.000000     -0.133885       0.001428   
YearsCodePro    0.872745   -0.133885      1.000000       0.010461   
ConvertedComp   0.010646    0.001428      0.010461       1.000000   
WorkWeekHrs     0.016252   -0.000632      0.016571       0.003351   
Age             0.780571    0.106806      0.818525       0.021344   

               WorkWeekHrs       Age  
YearsCode         0.016252  0.780571  
Age1stCode       -0.000632  0.106806  
YearsCodePro      0.016571  0.818525  
ConvertedComp     0.003351  0.021344  
WorkWeekHrs       1.000000  0.019976  
Age               0.019976  1.000000

In [88]:
df_base = df_answers[['YearsCode','Age1stCode','YearsCodePro','ConvertedComp','WorkWeekHrs','Age']]
df_base.dropna()

YearsCode  Age1stCode  YearsCodePro  ConvertedComp  WorkWeekHrs  \
Respondent                                                                    
3                 3.0        22.0           1.0       105840.0        40.00   
4                 3.0        16.0           1.0        61000.0        80.00   
6                13.0        15.0           3.0      4397040.0        15.00   
9                12.0        11.0           4.0        95179.0        32.00   
13               17.0        11.0           8.0        90000.0        40.00   
...               ...         ...           ...            ...          ...   
88877            31.0        18.0          28.0    104000000.0        45.00   
88878            12.0        14.0           3.0       130000.0        40.00   
88879            17.0        16.0           7.0       989856.0        37.75   
88881            18.0        17.0           9.0        68745.0        39.00   
88883             9.0        15.0           5.0        22915.0        48.00   

             Age  
Respondent        
3           28.0  
4           22.0  
6           28.0  
9           23.0  
13          28.0  
...          ...  
88877       48.0  
88878       26.0  
88879       34.0  
88881       37.0  
88883       33.0  

[52852 rows x 6 columns]

In [89]:
df_base.corr()

YearsCode  Age1stCode  YearsCodePro  ConvertedComp  \
YearsCode       1.000000   -0.246663      0.872745       0.010646   
Age1stCode     -0.246663    1.000000     -0.133885       0.001428   
YearsCodePro    0.872745   -0.133885      1.000000       0.010461   
ConvertedComp   0.010646    0.001428      0.010461       1.000000   
WorkWeekHrs     0.016252   -0.000632      0.016571       0.003351   
Age             0.780571    0.106806      0.818525       0.021344   

               WorkWeekHrs       Age  
YearsCode         0.016252  0.780571  
Age1stCode       -0.000632  0.106806  
YearsCodePro      0.016571  0.818525  
ConvertedComp     0.003351  0.021344  
WorkWeekHrs       1.000000  0.019976  
Age               0.019976  1.000000